services:
  lakefs-dev:
    image: treeverse/lakefs:1.7.0
    ports:
      - "8001:8000"
    environment:
      LAKEFS_INSTALLATION_USER_NAME: "admin"
      LAKEFS_INSTALLATION_ACCESS_KEY_ID: "access_key"
      LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: "secret_key"
      LAKEFS_DATABASE_TYPE: "local"
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "my-super-secret-key-for-encryption"
      LAKEFS_BLOCKSTORE_TYPE: "local"
    volumes:
      - lakefs_data:/data
    networks:
      - data_network

  prefect-agent:
    build:
      context: ./test-scraping
      dockerfile: Dockerfile
    container_name: prefect_agent
    volumes:
      - ./:/app
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - LAKEFS_ACCESS_KEY_ID=access_key
      - LAKEFS_SECRET_ACCESS_KEY=secret_key
      - LAKEFS_ENDPOINT_URL=http://lakefs-dev:8000
    depends_on:
      - lakefs-dev
      - prefect-server
    networks:
      - data_network

  prefect-server:
    image: prefecthq/prefect:3.4.1-python3.11
    container_name: prefect_server
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    command: prefect server start --host 0.0.0.0
    networks:
      - data_network

volumes:
  lakefs_data:
  prefect_data:

networks:
  data_network:
    driver: bridge